project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://hariprasadreddyk.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: mp01.qmd
        text: Mini Project 01
      - href: mp02.qmd
        text: Mini Project 02
      - href: mp03.qmd
        text: Mini Project 03
    
format:
  html:
    theme: cosmo
    toc: true
    toc-location: right

editor:
  mode: source